# Generated by Django 5.1.1 on 2024-09-25 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('loc_address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_first', models.CharField(max_length=50, null=True)),
                ('user_last', models.CharField(max_length=100, null=True)),
                ('card_balance', models.FloatField(null=True)),
                ('user_points', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('item_total', models.FloatField(null=True)),
                ('tax', models.FloatField(null=True)),
                ('tip', models.FloatField(null=True)),
                ('final_total', models.FloatField(null=True)),
                ('loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.location')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storeapp.product')),
            ],
        ),
    ]
